### ISSUE TITLE
ParseError: "ir.action.act_window" while parsing file

### ISSUE THREAD

**Issue by Mohamedyousif910** [rnrbarbosa/odoo-loans#6]
ParseError: "ir.action.act_window" while parsing file:///C:/Program%20Files%20(x86)/Odoo%2010.0/server/odoo/addons/university/view.xml:4, near
<record id="university_action" model="ir.action.act_window">
     		<field name="name">University</field>
     		<field name="res_model">university.student</field>
     		<field name="view_type">form</field>
     		<field name="view_mode">form,tree</field>
     	</record>

**Comment by rjpathan** [comment]
Error is not related to this app; it is related to app university
in file: university / view.xml
